version: 3.8

services:
  backend-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${PORT:-5522}:5522"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=postgres-db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    depends_on:
      - postgres-db
  postgres-db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend-api

volumes:
  pgdata:
