/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/client-sync/migration/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MantenimientoMigracionController_ejecutarEtl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/client-sync/migration/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener listado de clientes migrados con paginación */
        get: operations["ConsultaMigracionController_obtenerClientes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ObtenerClientesDto: {
            /**
             * @description Cantidad de elementos por página
             * @default 3
             * @example 10
             */
            limit: number;
            /**
             * @description Número de página a consultar
             * @default 1
             * @example 1
             */
            page: number;
            /**
             * @description Término de búsqueda
             * @example Juan
             */
            search?: string;
            /**
             * @description Estado del cliente
             * @example true
             */
            active?: boolean;
            /** @description Filtrar por estado de migración */
            migrado?: boolean;
        };
        TipoDocumentoDto: {
            /** @example 1 */
            id: number;
            /** @example DNI */
            abreviatura: string;
        };
        ClienteMigracionDto: {
            /** @example 1052 */
            legacyMysqlId: number;
            /**
             * Format: date-time
             * @example 2026-05-10T14:30:00.000Z
             */
            fechaMigracion: string;
            /** @example admin_user */
            usuarioMigrador?: string | null;
        };
        ObtenerClientesResponse: {
            /** @example cli_89f721a */
            publicKey: string;
            /** @example Juan Pérez */
            nombreCompleto: string;
            /** @example 72839102 */
            numeroDocumento: string;
            /** @example true */
            activo: boolean;
            tipoDocumento: components["schemas"]["TipoDocumentoDto"];
            clienteMigracion?: components["schemas"]["ClienteMigracionDto"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    MantenimientoMigracionController_ejecutarEtl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConsultaMigracionController_obtenerClientes: {
        parameters: {
            query?: {
                /** @description Cantidad de elementos por página */
                limit?: number;
                /** @description Número de página a consultar */
                page?: number;
                /** @description Término de búsqueda */
                search?: string;
                /** @description Estado del cliente */
                active?: boolean;
                /** @description Filtrar por estado de migración */
                migrado?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista paginada de clientes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObtenerClientesResponse"][];
                };
            };
        };
    };
}
